### ISSUE TITLE
NBA Teams() do not work

### ISSUE THREAD

**Issue by jiwoongim** [roclark/sportsipy#626]
The example code for NBA team does not work

```
from sportsipy.nba.teams import Teams

teams = Teams()
for team in teams:
    print(team.name, team.abbreviation)
```

I get an error:
```
(Pdb) Teams(year=year)
The requested page returned a valid response, but no data could be found. Has the season begun, and is the data available on www.sports-reference.com?

(Pdb) Teams(year=2001)
The requested page returned a valid response, but no data could be found. Has the season begun, and is the data available on www.sports-reference.com?

(Pdb) Teams()
The requested page returned a valid response, but no data could be found. Has the season begun, and is the data available on www.sports-reference.com?

(Pdb) from sportsipy.nba.teams import Teams
(Pdb) teams = Teams()
The requested page returned a valid response, but no data could be found. Has the season begun, and is the data available on www.sports-reference.com?
```

Not sure when  this started happening

This is because 
```
from pyquery import PyQuery as pq

(Pdb) doc = pq(SEASON_PAGE_URL % year)
(Pdb) doc
[<html.no-js>]

(Pdb) teams_list = utils._get_stats_table(doc, 'div#all_team-stats-base')
(Pdb) teams_list
(Pdb) opp_teams_list = utils._get_stats_table(doc, 'div#all_opponent-stats-base')
(Pdb) opp_teams_list

```

They are returns nothing

**Comment by joewilaj** [comment]
I think it is because the tables for the second round of playoffs are empty.

**Comment by joewilaj** [comment]
The entire nba package is no longer functional. 'no data could be found'

**Comment by jiwoongim** [comment]
@joewilaj @roclark   How long has this been?  How do these tasks get assigned? Wondering how long it will take them to fix this.

**Comment by joewilaj** [comment]
I just discovered this issue today. I had been using the package everyday for the past few months with with no error. I am not sure what needs to be fixed.

**Comment by deadlyeffect** [comment]
Would love an update on this

**Comment by jiwoongim** [comment]
I am not sure if someone is going to fix it. I am also curious whether this GitHub page is maintained by who? @roclark @ajhodges

**Comment by jsnider3** [comment]
I also need this fixed. Perhaps a fork would be necessary if this isn't being maintained any more?

**Comment by MarkGannon** [comment]
The div tag's id value changed on the teams pages.  Here is a diff with the fix for this issue: `diff --git a/sportsipy/nba/nba_utils.py b/sportsipy/nba/nba_utils.py
index 919edc4..0dd1209 100644
--- a/sportsipy/nba/nba_utils.py
+++ b/sportsipy/nba/nba_utils.py
@@ -82,8 +82,8 @@ def _retrieve_all_teams(year, season_file=None):
            utils._url_exists(SEASON_PAGE_URL % str(int(year) - 1)):
             year = str(int(year) - 1)
     doc = utils._pull_page(SEASON_PAGE_URL % year, season_file)
-    teams_list = utils._get_stats_table(doc, 'div#all_team-stats-base')
-    opp_teams_list = utils._get_stats_table(doc, 'div#all_opponent-stats-base')
+    teams_list = utils._get_stats_table(doc, 'div#div_confs_standings_E')
+    opp_teams_list = utils._get_stats_table(doc, 'div#div_confs_standings_W')
 
     if not teams_list and not opp_teams_list:
         utils._no_data_found()
`
When I try an push a new branch with the fix to the repository, I get this message: `git push origin fix_teams_div_id 
ERROR: Permission to roclark/sportsipy.git denied to MarkGannon.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

**Comment by deadlyeffect** [comment]
Thanks @MarkGannon! I had a feeling it was some simple HTML change on the source but CBA at the time. Appreciate it!

**Comment by jernej19** [comment]
Will anyone push the changes? I tried with getting a schedule for every team 
teams = Teams()
for team in teams:
    schedule = team.schedule()  # Returns a Schedule instance for each team
    # Returns a Pandas DataFrame of all metrics for all game Boxscores for
    # a season.
    df = team.schedule.dataframe_extended
    
  and I also get the same error

**Comment by mikeschopp** [comment]
Hey @roclark  thanks again for pulling this together! I've reinstalled the package and I'm unfortunately running into the same issue. Is there another version I should be using?
