### ISSUE TITLE
NFL team roster returns empty list

### ISSUE THREAD

**Issue by weningea** [roclark/sportsipy#677]
**Describe the bug**
Trying to access the NFL roster for any team across any year results in an empty list.

**To Reproduce**
The easiest way is to follow along with the [code in the docs](https://sportsreference.readthedocs.io/en/stable/nfl.html).
```python
from sportsipy.nfl.teams import Teams

for team in Teams():
    roster = team.roster
    for player in roster.players:
            print(player.name)
```
Players can still be referenced directly as far as I can tell, but lookup is difficulty because that requires the player ID.
Additionally, while you can reference team rosters directly with sportsipy.nfl.roster, only the coach name can be accessed.

**Expected behavior**
Players should be abled to be referenced from team rosters

**Screenshots**
![image](https://user-images.githubusercontent.com/38137357/144651737-2337eef9-b5f5-4f6f-aa6e-193ef0e953d4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Sportsipy Version: 0.6.0

If there's a better way to access player data, please let me know. Thank you.

**Comment by mcmichaelk** [comment]
Having a similar issue with the Roster class returning empty Dictionary.

**Replication**

Returning empty dictionary:

from sportsipy.nfl.teams import Teams
from sportsreference.nfl.roster import Roster

yr = 2020
tm = 'KAN'
roster = Roster(tm,yr, slim=True)

rosterDict = roster.players


print("Roster Dictionary:")
print(rosterDict)

**Result**:
Roster Dictionary:
{}

**Expected Result**:
Player name AND playerID for the given team and year (since slim is True)
